script:
  - curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.5/mdbook-v0.4.5-x86_64-unknown-linux-gnu.tar.gz > mdbook.tar.gz
  - tar -xvf mdbook.tar.gz
  - ./mdbook build
  - cd book
  # We don't use jekyll. Disable it so it doesn't assign special meaning to any
  # of our files (e.g. ignoring directories with a leading '_').
  - touch .nojekyll
branches:
  only:
    - master
deploy:
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: "CZv72syT/jfgW6zvS+A4BkQbRg37T6bjEnJ491eOrhZ5ZVED6Q1gcyDOZ8/ygfmdmiylhLh3YnM5I7jqzLZXsEP1RtgppfAG5/OPoiCzvzBidUttSsTCJRfog+xyXjDwd5Z2d0uMiY0mAUe6RTmekCf09OSd/3HCZcAeRpuKJM79qZ7jqYxUbyXD0PsXqJ8J3WI16TGBO9NvJtalxlmrBuYr2tLyMq17S8MVhwVAvRAZQMI68Zc8Fpb5wRaxzchAPxN5pBoZJGt/fszULEH4TMhU6DCM+uFM8I5isKk5mBgzUy2nib2ScqEDbdd1t33gzufgPf9Z+X6A0bBD4bLrrk4xUl+cp8t4qCu4qDGZh7YBm7IKIK8ZL9kL9VP7X5tJAQ1+hmtvmKxHDvOv2DfsXSoLYp5lWaMRYes4Ao27SeapS+Q/BQ+tw3sqH/a/ymqruRqrBYrRuSgTLHHwh+PDIFj6DzWbJuIJ3iP9ArIGNbl9fkBjnZpsaBlM85O2qYA+6w7kynyYLwgPhDma44pXQNBRZZn2AKe5L16ZM5fq5za3U3U3E7Z5AOvfOAz1r3prJMmdQkZju0uawfcBkaLczvt8zXT83ukKay6xvI1WWU2n5/QbInIghzEzYIW/ey0HqnquQLNpRYDpblXAo2aqZVo+nKPKqJzGpm+6kYpF8Mg="
    keep-history: true
    local-dir: book
    repo: bors-ng/rfcs
